GDG-IGDTUW/DSA-2

Warehouse Inventory Management/vanshika-aggarwal1--warehouse.cpp

CPP solution for warehouse inventory management with solutions to the given problem in the file vanshika-aggarwal1--warehouse.

Warehouse Inventory Management

---

Student Attendance Management System/Manyapahwa--StudentAttendance.cpp

This pull request adds the implementation of a Student Attendance Management System. The system provides functionality to:
Add a Student: Allows registering a student with their name, roll number, and class.
Mark Attendance: Enables marking attendance as Present, Absent, or Late for a specific student.
View Attendance: Displays the full attendance record of a student.
Remove a Student: Removes a student’s record from the system permanently.

student attendance management system code added

---

Parking Lot Management System/Neha2918--ParkingLotManagementSystem.cpp

Added solution to implement a Parking Lot Management System using a stack-based approach for efficient parking spot allocation and deallocation. It supports parking and removing vehicles, calculates fees based on a fixed rate of ₹20/hour, and adheres to the constraint of 1 <= total_spots <= 1000. The system uses stacks to manage parking spots and hash maps to track vehicle details, ensuring operations are performed in O(1) time. Edge cases like full parking and invalid vehicle removal are handled, and the solution is tested for correctness and efficiency.
Time Complexity:
parkVehicle: O(1) for parking spot allocation.
removeVehicle: O(1) for spot deallocation and fee calculation.
Space Complexity: O(n), where n is the total number of parking spots.

 issue #6 Parking Lot Management System.cpp

---

Task Management System/vanshika-aggarwal1--task.cpp

Created the solution for Task Management System in CPP

CPP solution for task management system

---

Library Management System/Manyapahwa-LibraryManagementSystem.cpp

This code implements a simple Library Management System in C++ that allows users to manage books, borrowers etc.

Added Library Management System solution #4 issue

---

Social Network Friend Recommendation/Neha2918--SocialNetworkFriendRecommendation.cpp

Introduced a solution for generating friend recommendations in a social network based on mutual connections. The algorithm identifies users who share mutual friends and suggests them as potential connections. It is designed to help enhance user engagement by recommending friends who are connected to the user's existing network.
Uses a graph-like structure where users are nodes, and friendships are edges.
For each user, it identifies mutual friends from their friends' list and recommends them as potential friends.
Implements efficient data structures to ensure quick lookups and recommendations.
Time Complexity: O(n + m) where n is the number of users (nodes) and m is the number of friendships (edges). The algorithm processes all users and their connections.
Space Complexity: O(n + m) 
The …

issue #1 Social Network Friend Recommendation.cpp

---

Parking Lot Management System/Parking Lot Management System.java

Added parking Lot management System in java with proper comments and same variables as in cpp for easiness to understand.

Parking Lot Management System - Java

---

Social Network Friend Recommendation/vanshika-aggarwal1--social.cpp

CPP solution for Social Network Friend Recommendation

CPP Solution

---

Bus Route Planner/bus route planner.cpp

Bus Route Planner #9 solution

---

Financial Transaction Processor/ManushreeGrover--Financial Transaction Processor.java

Added the improved code in java language with all constraints.

#issue 2 - Financial Transaction Processor

---

Task Management System/SonamKumari29_task_mgmt_sys.java

issue #3  java solution added .kindly review:) @sriya-singh

Task Management System Java solution added

---

Food Delivery System/KashishJuneja101003_Food_Delivery_System.cpp

**Issue:** #5 
The provided code now includes:
1. **Input Validation:** Added checks for valid email, phone numbers, and empty fields during user registration.
2. **Error Handling:** Managed cases where invalid items or prices are added to menus and orders, and ensured meaningful messages are shown to the user.
3. **Order Validation:** Ensured only valid items are processed in orders.
4. **Better Feedback:** Added clear messages for successful and failed actions.

Added input validation, Error Handling, Order Validation and Better Feedback

---

Parking Lot Management System/SonamKumari29_ParkingLotMgmtSys.java

issue #6  
Parking Lot Management System java solution added 
Time Complexity:
park: O(1) – Direct access to stack and map.
remove: O(1) – Direct access to map for vehicle and stack for spot.
Space Complexity:
O(N) – For storing N vehicles and parking spots.
kindly review and merge:)  @manasi584 @praggyaverma

Parking Lot Management System java solution added 

---

Financial Transaction Processor/KashishJuneja101003--Financial-Transaction-Processor.cpp

**Issue:** #2 
Kindly review the code.
@sriya-singh @nishisharma842004 
This PR improves the FinancialTransactionProcessor class by refactoring the transaction handling logic for better readability, maintainability, and efficiency. The key improvements include:
✅ Replaced string transaction types with enum class for better type safety and efficiency.
✅ Added a constructor to Transaction struct for easier object initialization.
✅ Separated balance update logic into a dedicated method to improve code organization.
✅ Passed transactions as const vector<Transaction>& to avoid unnecessary copying.
✅ Enhanced isValidTransaction() with explicit checks for different transaction types.
🔹 Why These Changes?
Using enum class prevents errors due to string mismatches.
A dedicated updateBalance() …

Create and Refactored FinancialTransactionProcessor for Efficiency and Readability in cpp

---

Task Management System/KashishJuneja101003--Task-Management-System.cpp

Issue: #3 
@sriya-singh @Pallavi1926 
Kindly review the code.
This PR improves the TaskManager class by optimizing task management operations using a priority queue (max-heap) and an unordered map (hash map). The previous implementation relied on a vector with manual sorting, which was inefficient for frequent operations.
**Key Improvements**
✅ Implemented Missing Functions:
- addTask(int id, int time, int priority): Adds tasks efficiently.
- getHighestPriorityTask(): Retrieves the highest-priority task in O(1) time.
- removeTask(int id): Deletes tasks efficiently using O(1) lookup.
✅ Optimized Task Retrieval Using a Priority Queue (max-heap)
- Ensures higher priority tasks are returned first.
- If two tasks have the same priority, the one with earlier time is preferred.
- Eliminates the …

Create and Optimize TaskManager using Priority Queue and Hash Map

---

Library Management System/SonamKumari29_LibraryMgmtSys.java
Parking Lot Management System/SonamKumari29_ParkingLotMgmtSys.java

Implemented a Java-based Library Management System with features to add, search, borrow, return, and view books using a HashMap for efficient storage (O(1) average time complexity for insert/search). The system ensures proper book availability checks and user interaction via a menu-driven approach. Space complexity is O(N), where N is the number of books. Optimized error handling and improved code readability with comments. Kindly review @shreya22gaur @sriya-singh

Library Management System java solution added

---

Task Management System/KashishJuneja101003--Task-Management-System.cpp

This PR enhances the existing Task Manager implementation by introducing additional functionalities while improving efficiency.
**Key Enhancements:**
1. Update Task (queryType = 4)
- Allows modifying an existing task's time and priority.
- If the task exists, it is removed and reinserted with updated values.
2. List All Tasks (queryType = 7)
- Displays all tasks sorted by priority (descending) and time (ascending) for same-priority tasks.
3. Check Task Existence (queryType = 5)
- Checks whether a task exists in the system.
4. Optimized Priority Queue Handling
- Ensures that removed tasks do not affect priority retrieval.
Issue: #3 
@sriya-singh 
Kindly review the code.

Enhance Task Manager: Add Update, List, and Existence Check Features

---

Student Attendance Management System/KashishJuneja101003--Student-Attendance-Management-System.cpp

Issue: #7 
Kindly review the code :)
@sriya-singh @praggyaverma
This PR enhances the Student Attendance Management System by improving code structure, implementing better memory management, and adding input validation. The improvements ensure the system is more efficient, robust, and user-friendly.
🔧 Key Improvements
✅ Used enum for Attendance Status → Prevents invalid status entries.
✅ Implemented unordered_map<int, Student*> → Efficient memory management with pointers.
✅ Added Destructor (~AttendanceSystem()) → Prevents memory leaks by deallocating memory.
✅ Created getInputString() Function → Properly handles multi-word input.
✅ Validated User Input for Attendance Status → Ensures valid entries (Present, Absent, Late).
✅ Improved User Messages → Provides clear feedback for actions. …

Improved Student Attendance Management System

---

Financial Transaction Processor/KashishJuneja101003--Financial-Transaction-Processor.cpp

Issue: #2 
Kindly review the code :)
@sriya-singh @nishisharma842004
This PR enhances the Financial Transaction Processor by implementing better validation, optimized fee calculation, and improved error handling. The key improvements include:
✅ Correct Fee Deduction:
- Ensures fees are only deducted for withdrawals and transfers, not deposits.
✅ Improved Transaction Validation:
- Prevents negative balances due to insufficient funds.
- Ensures valid transaction amounts (no negative values).
✅ Optimized Fee Calculation:
- Introduces a calculateFee() method for better modularity and flexibility.
✅ Better Output Formatting & Reporting:
- Uses fixed << setprecision(2) for currency format clarity.
- Provides clearer console output for transaction summaries.
✅ Fails Gracefully for Invalid …

Enhance Financial Transaction Processor with Improved Validation and Fee Handling

---

Financial Transaction Processor/Financial Transaction Processor in cpp

cpp solution for financial transaction processor

Create Financial Transaction Processor in cpp

---

Financial Transaction Processor/SonamKumari29_FinancialTransactionProcessor.java

issue #2 
Added Financial transaction processor java solution to process financial transactions efficiently.
Time Complexity: (O(N)), where (N) is the number of transactions (each transaction is processed once).
Space Complexity: (O(1)), as only a few integer variables are used (no extra data structures).
Handles deposits, withdrawals, and transfers with constraints on transaction hours, limits, and minimum balance requirements.
kindly review @sriya-singh @sriya-singh

financial transaction processor java solution added

---

Student Attendance Management System/KashishJuneja101003--Student-Attendance-Management-System.cpp

Issue: #7 
Kindly review the code :)
@sriya-singh @praggyaverma
1. Smart Pointers (unique_ptr) – Eliminated manual memory management by replacing new and delete with unique_ptr, preventing memory leaks.
2. File Handling for Data Persistence – Added functionality to save and load student data from a file (students.txt), ensuring attendance records persist across sessions.
3. Improved Input Handling – Fixed cin.ignore() issues by correctly handling newline characters before getline().
4. Enhanced Readability & Formatting –
- Introduced Enums (AttendanceStatus) to replace magic numbers for attendance marking.
- Improved attendance display formatting for better readability.
5. Duplicate Student Check – Prevents students with the same roll number from being added multiple times.
6. Looped …

 Improved Student Attendance Management System – Smart Pointers, File Handling & Code Cleanup

---

Task Management System/KashishJuneja101003--Task-Management-System.cpp

Issue: #3 
@sriya-singh
Kindly review the code.
1. Enhanced Task Lookup & Removal
- Introduced a bidirectional mapping (unordered_map<int, set<Task>::iterator>) for O(1) lookup and O(log n) updates/removals.
- Eliminated redundant removal-insertion cycles in updateTask(), reducing unnecessary operations.
2. Improved Data Safety & Code Readability
- Used structured bindings for cleaner access to Task fields.
- Enhanced exception handling for invalid operations (e.g., accessing non-existent tasks).
3. Better Input Handling
- Extracted user interaction logic into a separate function (handleUserInput()), making main() cleaner.
4. Optimized Console Output
- listAllTasks() now displays tasks in a formatted tabular format, improving readability.
**Output:**

Optimized Task Manager Implementation

---

Financial Transaction Processor/KashishJuneja101003--Financial-Transaction-Processor.cpp

Issue: #2 
Kindly review the code :)
@sriya-singh @nishisharma842004
1. Dynamic User Input Handling
- Users can now enter transactions at runtime instead of relying on hardcoded values.
-  Includes error handling to prevent crashes due to invalid inputs.
2. More Realistic & Flexible Fee Calculation
- Transaction fees are now dynamic:
- Deposits remain fee-free.
- Withdrawals and Transfers have base fees but increase during peak hours (9 AM - 6 PM).
- Peak hour transactions incur a 1.5x fee multiplier.
3. Transaction Logging & Improved Output Formatting
- Maintains a history log of successful transactions.
- Displays transaction details in a structured tabular format using setw().
- Final balance and fee summary are formatted for better readability.
4. Optimized Transaction Processing
- …

Enhancing Financial Transaction Processing System

---

Student Attendance Management System/SonamKumari29_StudentAttendanceMgmtSys.java

issue #7 
Implemented Student Attendance Management System in java tracking using HashMap for O(1) operations. Added CLI for adding students, marking/viewing attendance, and removal.
Complexity:
Add/Remove: O(1)
Mark Attendance: O(1)
View Attendance: O(N)
kindly review @manasi584 @praggyaverma

Student Attendance Management System Java solution added

---

Bus Route Planner/SonamKumari29_BusRoutePlanner.java

issue #9 implemented bus route planner in java to find the shortest travel time and penalty between bus stops, considering maximum transfers, service hours, and penalties. Uses Dijkstra’s algorithm.
Time Complexity: O(m log n)
Space Complexity: O(m + n)
kindly review @manasi584 @manasi584

Bus route planner java solution added

---

Social Network Friend Recommendation/manasvi9745--Social Network Friend Recommendation.py

Approach :
the social network is represented  as an undirected graph where:
Users are nodes (vertices).
Friendships are edges.
Friend recommendations are found using BFS (Breadth-First Search).
Time & Space Complexity:
Add User: O(1)
Add Friendship: O(1)
View Friends: O(1)
Friend Recommendations (BFS):  O(V+E), where V = users, E = friendships.

Issue #1 Social Network Friend Recommendation  python solution added- manasvi 

---

Parking Lot Management System/parking_lot_management_system.py

This code resolves #6  using Python.

Adding python submission for parking lot management system

---

Warehouse Inventory Management/warehouse_inventory_mgmt_system.py

This code resolves #10   using python
Sample output:

Adding python submission for warehouse inventory management system - Saumya

---

Financial Transaction Processor/financial_transaction_processor.py

This code resolves #2  using Python.
Sample output:

Adding python solution for Financial Transaction Processor

---

Bus Route Planner/bus_route_planner.py

This code resolves #9 using Python.
Sample output:

Adding python solution for Bus Route Planner

---

Library Management System/library_mgmt_system.py

This code resolves #4 using python.
Sample output:

Adding python solution for Library Management System

---

Student Attendance Management System/student_attendance_mgmt_system.py

This code resolves #7  using python.
Sample output:

Adding python solution for Student Attendance Management System

---

Task Management System/task_mgmt_system.py

This code resolves #3  using python
Sample output:

Adding python solution Task Management System - Saumya

---

Social Network Friend Recommendation/social_network_friend_recommendation.py

This code resolves #1 using python. 
Sample output:

Adding Python solution for Social Network Friend Recommendation - Saumya

---

Food Delivery System/food_delivery_system.py

This code resolves #5 using python.
Sample output:

Adding python solution for Food Delivery System

---

Movie Booking System/movie_booking.py

This code resolves #8  using python
Sample output:

Adding python solution for Movie Booking System
